---
title: "Hitter clustering"
author: "Samuel Brown"
date: "2023-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
ggplot2::theme_set(ggplot2::theme_bw()) 
library(tidyverse)
```

# Read in data
```{r}
files <- list.files(pattern = "2022", full.names = TRUE)
pitcher_ids <- read.csv("pitcher_ids.csv")
batter_ids <- read.csv("hitter_ids.csv")
all_pitches <- Reduce(rbind, lapply(files, read.csv)) %>%
  filter(balls < 4 & strikes < 3) %>%
  unite("count", balls, strikes, remove = FALSE) %>%
  unite("matchup", stand, p_throws, remove = FALSE) %>% 
  inner_join(pitcher_ids, by = "pitcher") %>% 
  inner_join(batter_ids, by = "batter")

rm(pitcher_ids)
rm(batter_ids)
```

# Make hitter clustering data
```{r}
# Cluster on power(95th percentile exit velo) plus O-Swing%, Z-Swing, Z-contact
hitter_data <- all_pitches %>% 
  mutate(in_zone = plate_z <= sz_top & plate_z >= sz_bot & plate_x <= .708 & plate_x >= -.708,
         #in_zone = zone <= 9
         swing = description %in% c("swinging_strike", "hit_into_play", "foul", "foul_tip", 
                                    "foul_bunt", "swinging_strike_blocked", "missed_bunt"),
         whiff = description %in% c("swinging_strike_blocked", "swinging_strike", "foul_tip")) %>% 
  group_by(batter, hitter_name) %>% 
  summarize(balls_in_play = sum(!is.na(launch_speed) & description != "foul"),
            exit_velo_95 = quantile(launch_speed, .95, na.rm = TRUE),
            O_swing = sum(swing & !in_zone)/sum(!in_zone),
            Z_swing = sum(swing & in_zone)/sum(in_zone),
            Z_contact = sum(swing & !whiff & in_zone)/sum(swing & in_zone),
            LA = mean(launch_angle, na.rm = TRUE),
            wOBA = sum(woba_value, na.rm = TRUE)/sum(woba_denom, na.rm = TRUE),
            .groups = 'drop') 

head(hitter_data)
```

### Find stabilization point of exit velo and filter for that point
```{r}
ggplot(hitter_data, aes(x = balls_in_play, y = LA)) +
  geom_point()
```

```{r}
# Filter for stabilization point
hitter_data <- hitter_data %>% 
  filter(balls_in_play >= 75) %>% 
  select(-balls_in_play)
# Scale hitter data
scale_z <- function(x) (x - mean(x, na.rm = T)) / sd(x, na.rm = T)
scaled_hitters <- hitter_data %>% 
  select(where(is.numeric) & !batter & !wOBA) %>% 
  mutate(across(where(is.numeric), 
               scale_z),
         O_swing = O_swing * .5,
         Z_swing = Z_swing * .5
         ) %>% 
  drop_na()

head(hitter_data)
```

### SVD?
```{r}
# SVD on hitter_data
hist(svd(scaled_hitters %>% as.matrix())$u[,1])
svd(scaled_hitters %>% as.matrix())$d
```

# K Means
```{r}
test_centers <- function(i, df){
  # Make the clusters with i centers
  test_cluster <- df %>% 
    kmeans(centers = i, nstart = 5, iter.max = 300)
  # Find how effective
  return(test_cluster$tot.withinss)
}

# Find an elbow
test_cluster_list <- 1:9
test_cluster_results <- sapply(test_cluster_list, test_centers, 
                               df = scaled_hitters)
test_cluster_results %>% 
  data.frame(clusters = test_cluster_list,
             total_within_ss = .) %>% 
  ggplot(aes(x = clusters, y = log(total_within_ss))) +
  geom_point() +
  geom_line() 
```

```{r}
# Cluster the hitters
hitter_kmeans <- scaled_hitters %>% 
  kmeans(centers = 3, nstart = 10, iter.max = 1000)
hitter_clusters <- cbind(hitter_data %>% drop_na(),
      cluster = hitter_kmeans$cluster)

# Find group averages
hitter_clusters %>% 
  group_by(cluster) %>% 
  summarize(exit_velo_95 = mean(exit_velo_95),
            O_swing = mean(O_swing),
            Z_swing = mean(Z_swing),
            Z_contact = mean(Z_contact),
            LA = mean(LA))
```

# Hierarchical clustering
### Make dendrogram
```{r}
hitter_hclust <- hclust(dist(scaled_hitters), method = "ward.D2")

plot(hitter_hclust)
```

### Look at different clusters
```{r}
hier_hitters <- cbind(hitter_data, cluster = as.factor(cutree(hitter_hclust, k = 4)))

hier_hitters %>% 
  group_by(cluster) %>% 
  summarize(exit_velo_95 = mean(exit_velo_95),
            O_swing = mean(O_swing),
            Z_swing = mean(Z_swing),
            Z_contact = mean(Z_contact),
            LA = mean(LA),
            wOBA = mean(wOBA))

hier_hitters %>% 
  filter(cluster == 1) %>% 
  arrange(-wOBA) 
hier_hitters %>% 
  filter(cluster == 2) %>% 
  arrange(-wOBA) 
hier_hitters %>% 
  filter(cluster == 3) %>% 
  arrange(-wOBA) 
hier_hitters %>% 
  filter(cluster == 4) %>% 
  arrange(-wOBA) 
```

# Write that down
```{r}
write.csv(hier_hitters, "clustered_hitters.csv", row.names = FALSE)
```

